define([], function() {

return [
  {"year":1950,"rank":"1","country":"United States of America","agglomeration":"New York","population":12.34},
  {"year":1950,"rank":"2","country":"Japan","agglomeration":"Tokyo","population":11.27},
  {"year":1950,"rank":"3","country":"United Kingdom","agglomeration":"London","population":8.36},
  {"year":1950,"rank":"4","country":"France","agglomeration":"Paris","population":6.28},
  {"year":1950,"rank":"5","country":"Russian Federation","agglomeration":"Moscow","population":5.36},
  {"year":1950,"rank":"6","country":"Argentina","agglomeration":"Buenos Aires","population":5.1},
  {"year":1950,"rank":"7","country":"United States of America","agglomeration":"Chicago","population":5},
  {"year":1950,"rank":"8","country":"India","agglomeration":"Calcutta","population":4.51},
  {"year":1950,"rank":"9","country":"China","agglomeration":"Shanghai","population":4.3},
  {"year":1950,"rank":"10","country":"Japan","agglomeration":"Osaka-Kobe","population":4.15},
  {"year":1950,"rank":"11","country":"United States of America","agglomeration":"Los Angeles","population":4.05},
  {"year":1950,"rank":"12","country":"Germany","agglomeration":"Berlin","population":3.34},
  {"year":1950,"rank":"13","country":"United States of America","agglomeration":"Philadelphia","population":3.13},
  {"year":1950,"rank":"14","country":"Brazil","agglomeration":"Rio de Janeiro","population":2.95},
  {"year":1950,"rank":"15","country":"Russian Federation","agglomeration":"Saint Petersburg","population":2.9},
  {"year":1950,"rank":"16","country":"Mexico","agglomeration":"Mexico City","population":2.88},
  {"year":1950,"rank":"17","country":"India","agglomeration":"Bombay","population":2.86},
  {"year":1950,"rank":"18","country":"United States of America","agglomeration":"Detroit","population":2.77},
  {"year":1950,"rank":"19","country":"United States of America","agglomeration":"Boston","population":2.55},
  {"year":1950,"rank":"20","country":"Egypt","agglomeration":"Cairo","population":2.49},
  {"year":1950,"rank":"21","country":"China","agglomeration":"Tianjin","population":2.47},
  {"year":1950,"rank":"22","country":"United Kingdom","agglomeration":"Manchester","population":2.42},
  {"year":1950,"rank":"23","country":"Brazil","agglomeration":"São Paulo","population":2.33},
  {"year":1950,"rank":"24","country":"United Kingdom","agglomeration":"Birmingham","population":2.23},
  {"year":1950,"rank":"25","country":"China","agglomeration":"Shenyang","population":2.15},
  {"year":1950,"rank":"26","country":"Italy","agglomeration":"Rome","population":1.88},
  {"year":1950,"rank":"27","country":"Italy","agglomeration":"Milan","population":1.88},
  {"year":1950,"rank":"28","country":"United States of America","agglomeration":"San Francisco","population":1.86},
  {"year":1950,"rank":"29","country":"Spain","agglomeration":"Barcelona","population":1.81},
  {"year":1950,"rank":"30","country":"United Kingdom","agglomeration":"Glasgow","population":1.76},
  {"year":1955,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":13.71},
  {"year":1955,"rank":"2","country":"United States of America","agglomeration":"New York","population":13.22},
  {"year":1955,"rank":"3","country":"United Kingdom","agglomeration":"London","population":8.28},
  {"year":1955,"rank":"4","country":"France","agglomeration":"Paris","population":6.8},
  {"year":1955,"rank":"5","country":"China","agglomeration":"Shanghai","population":5.85},
  {"year":1955,"rank":"6","country":"Argentina","agglomeration":"Buenos Aires","population":5.8},
  {"year":1955,"rank":"7","country":"Russian Federation","agglomeration":"Moscow","population":5.75},
  {"year":1955,"rank":"8","country":"United States of America","agglomeration":"Chicago","population":5.56},
  {"year":1955,"rank":"9","country":"United States of America","agglomeration":"Los Angeles","population":5.15},
  {"year":1955,"rank":"10","country":"Japan","agglomeration":"Osaka-Kobe","population":5.12},
  {"year":1955,"rank":"11","country":"India","agglomeration":"Calcutta","population":5.06},
  {"year":1955,"rank":"12","country":"Mexico","agglomeration":"Mexico City","population":3.8},
  {"year":1955,"rank":"13","country":"Brazil","agglomeration":"Rio de Janeiro","population":3.59},
  {"year":1955,"rank":"14","country":"United States of America","agglomeration":"Philadelphia","population":3.51},
  {"year":1955,"rank":"15","country":"India","agglomeration":"Bombay","population":3.43},
  {"year":1955,"rank":"16","country":"Germany","agglomeration":"Berlin","population":3.3},
  {"year":1955,"rank":"17","country":"Russian Federation","agglomeration":"Saint Petersburg","population":3.14},
  {"year":1955,"rank":"18","country":"United States of America","agglomeration":"Detroit","population":3.14},
  {"year":1955,"rank":"19","country":"Brazil","agglomeration":"São Paulo","population":3.04},
  {"year":1955,"rank":"20","country":"Egypt","agglomeration":"Cairo","population":3.03},
  {"year":1955,"rank":"21","country":"China","agglomeration":"Tianjin","population":2.76},
  {"year":1955,"rank":"22","country":"United States of America","agglomeration":"Boston","population":2.68},
  {"year":1955,"rank":"23","country":"United Kingdom","agglomeration":"Manchester","population":2.42},
  {"year":1955,"rank":"24","country":"China","agglomeration":"Shenyang","population":2.41},
  {"year":1955,"rank":"25","country":"China","agglomeration":"Beijing","population":2.36},
  {"year":1955,"rank":"26","country":"United Kingdom","agglomeration":"Birmingham","population":2.28},
  {"year":1955,"rank":"27","country":"Italy","agglomeration":"Rome","population":2.14},
  {"year":1955,"rank":"28","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":2.12},
  {"year":1955,"rank":"29","country":"Spain","agglomeration":"Barcelona","population":2.1},
  {"year":1955,"rank":"30","country":"Italy","agglomeration":"Milan","population":2.1},
  {"year":1960,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":16.68},
  {"year":1960,"rank":"2","country":"United States of America","agglomeration":"New York","population":14.16},
  {"year":1960,"rank":"3","country":"United Kingdom","agglomeration":"London","population":8.2},
  {"year":1960,"rank":"4","country":"France","agglomeration":"Paris","population":7.41},
  {"year":1960,"rank":"5","country":"China","agglomeration":"Shanghai","population":6.82},
  {"year":1960,"rank":"6","country":"Argentina","agglomeration":"Buenos Aires","population":6.6},
  {"year":1960,"rank":"7","country":"United States of America","agglomeration":"Los Angeles","population":6.53},
  {"year":1960,"rank":"8","country":"Japan","agglomeration":"Osaka-Kobe","population":6.23},
  {"year":1960,"rank":"9","country":"United States of America","agglomeration":"Chicago","population":6.18},
  {"year":1960,"rank":"10","country":"Russian Federation","agglomeration":"Moscow","population":6.17},
  {"year":1960,"rank":"11","country":"India","agglomeration":"Calcutta","population":5.65},
  {"year":1960,"rank":"12","country":"Mexico","agglomeration":"Mexico City","population":5.01},
  {"year":1960,"rank":"13","country":"Brazil","agglomeration":"Rio de Janeiro","population":4.37},
  {"year":1960,"rank":"14","country":"India","agglomeration":"Bombay","population":4.06},
  {"year":1960,"rank":"15","country":"Brazil","agglomeration":"São Paulo","population":3.97},
  {"year":1960,"rank":"16","country":"United States of America","agglomeration":"Philadelphia","population":3.93},
  {"year":1960,"rank":"17","country":"China","agglomeration":"Beijing","population":3.9},
  {"year":1960,"rank":"18","country":"Egypt","agglomeration":"Cairo","population":3.68},
  {"year":1960,"rank":"19","country":"United States of America","agglomeration":"Detroit","population":3.55},
  {"year":1960,"rank":"20","country":"Russian Federation","agglomeration":"Saint Petersburg","population":3.4},
  {"year":1960,"rank":"21","country":"Germany","agglomeration":"Berlin","population":3.26},
  {"year":1960,"rank":"22","country":"China","agglomeration":"Tianjin","population":2.94},
  {"year":1960,"rank":"23","country":"United States of America","agglomeration":"Boston","population":2.82},
  {"year":1960,"rank":"24","country":"China","agglomeration":"Shenyang","population":2.7},
  {"year":1960,"rank":"25","country":"Indonesia","agglomeration":"Jakarta","population":2.68},
  {"year":1960,"rank":"26","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":2.62},
  {"year":1960,"rank":"27","country":"Spain","agglomeration":"Barcelona","population":2.47},
  {"year":1960,"rank":"28","country":"Italy","agglomeration":"Rome","population":2.46},
  {"year":1960,"rank":"29","country":"United Kingdom","agglomeration":"Manchester","population":2.43},
  {"year":1960,"rank":"30","country":"Italy","agglomeration":"Milan","population":2.4},
  {"year":1965,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":20.28},
  {"year":1965,"rank":"2","country":"United States of America","agglomeration":"New York","population":15.18},
  {"year":1965,"rank":"3","country":"United Kingdom","agglomeration":"London","population":7.87},
  {"year":1965,"rank":"4","country":"France","agglomeration":"Paris","population":7.86},
  {"year":1965,"rank":"5","country":"Japan","agglomeration":"Osaka-Kobe","population":7.65},
  {"year":1965,"rank":"6","country":"United States of America","agglomeration":"Los Angeles","population":7.41},
  {"year":1965,"rank":"7","country":"Argentina","agglomeration":"Buenos Aires","population":7.32},
  {"year":1965,"rank":"8","country":"Mexico","agglomeration":"Mexico City","population":6.65},
  {"year":1965,"rank":"9","country":"United States of America","agglomeration":"Chicago","population":6.64},
  {"year":1965,"rank":"10","country":"Russian Federation","agglomeration":"Moscow","population":6.62},
  {"year":1965,"rank":"11","country":"China","agglomeration":"Shanghai","population":6.43},
  {"year":1965,"rank":"12","country":"India","agglomeration":"Calcutta","population":6.26},
  {"year":1965,"rank":"13","country":"Brazil","agglomeration":"São Paulo","population":5.49},
  {"year":1965,"rank":"14","country":"Brazil","agglomeration":"Rio de Janeiro","population":5.39},
  {"year":1965,"rank":"15","country":"India","agglomeration":"Bombay","population":4.85},
  {"year":1965,"rank":"16","country":"Egypt","agglomeration":"Cairo","population":4.74},
  {"year":1965,"rank":"17","country":"China","agglomeration":"Beijing","population":4.58},
  {"year":1965,"rank":"18","country":"United States of America","agglomeration":"Philadelphia","population":4.16},
  {"year":1965,"rank":"19","country":"United States of America","agglomeration":"Detroit","population":3.76},
  {"year":1965,"rank":"20","country":"Russian Federation","agglomeration":"Saint Petersburg","population":3.68},
  {"year":1965,"rank":"21","country":"Republic of Korea","agglomeration":"Seoul","population":3.45},
  {"year":1965,"rank":"22","country":"Indonesia","agglomeration":"Jakarta","population":3.3},
  {"year":1965,"rank":"23","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":3.29},
  {"year":1965,"rank":"24","country":"Germany","agglomeration":"Berlin","population":3.23},
  {"year":1965,"rank":"25","country":"China","agglomeration":"Tianjin","population":3.12},
  {"year":1965,"rank":"26","country":"United States of America","agglomeration":"Boston","population":3},
  {"year":1965,"rank":"27","country":"Spain","agglomeration":"Barcelona","population":2.93},
  {"year":1965,"rank":"28","country":"China","agglomeration":"Shenyang","population":2.92},
  {"year":1965,"rank":"29","country":"Spain","agglomeration":"Madrid","population":2.9},
  {"year":1965,"rank":"30","country":"India","agglomeration":"Delhi","population":2.85},
  {"year":1970,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":23.3},
  {"year":1970,"rank":"2","country":"United States of America","agglomeration":"New York","population":16.19},
  {"year":1970,"rank":"3","country":"Japan","agglomeration":"Osaka-Kobe","population":9.41},
  {"year":1970,"rank":"4","country":"Mexico","agglomeration":"Mexico City","population":8.77},
  {"year":1970,"rank":"5","country":"United States of America","agglomeration":"Los Angeles","population":8.38},
  {"year":1970,"rank":"6","country":"France","agglomeration":"Paris","population":8.21},
  {"year":1970,"rank":"7","country":"Argentina","agglomeration":"Buenos Aires","population":8.1},
  {"year":1970,"rank":"8","country":"Brazil","agglomeration":"São Paulo","population":7.62},
  {"year":1970,"rank":"9","country":"United Kingdom","agglomeration":"London","population":7.51},
  {"year":1970,"rank":"10","country":"Russian Federation","agglomeration":"Moscow","population":7.11},
  {"year":1970,"rank":"11","country":"United States of America","agglomeration":"Chicago","population":7.11},
  {"year":1970,"rank":"12","country":"India","agglomeration":"Calcutta","population":6.93},
  {"year":1970,"rank":"13","country":"Brazil","agglomeration":"Rio de Janeiro","population":6.64},
  {"year":1970,"rank":"14","country":"China","agglomeration":"Shanghai","population":6.04},
  {"year":1970,"rank":"15","country":"India","agglomeration":"Bombay","population":5.81},
  {"year":1970,"rank":"16","country":"Egypt","agglomeration":"Cairo","population":5.58},
  {"year":1970,"rank":"17","country":"Republic of Korea","agglomeration":"Seoul","population":5.31},
  {"year":1970,"rank":"18","country":"China","agglomeration":"Beijing","population":4.43},
  {"year":1970,"rank":"19","country":"United States of America","agglomeration":"Philadelphia","population":4.4},
  {"year":1970,"rank":"20","country":"Russian Federation","agglomeration":"Saint Petersburg","population":3.98},
  {"year":1970,"rank":"21","country":"United States of America","agglomeration":"Detroit","population":3.97},
  {"year":1970,"rank":"22","country":"Indonesia","agglomeration":"Jakarta","population":3.92},
  {"year":1970,"rank":"23","country":"Philippines","agglomeration":"Manila","population":3.53},
  {"year":1970,"rank":"24","country":"India","agglomeration":"Delhi","population":3.53},
  {"year":1970,"rank":"25","country":"Spain","agglomeration":"Madrid","population":3.52},
  {"year":1970,"rank":"26","country":"Spain","agglomeration":"Barcelona","population":3.48},
  {"year":1970,"rank":"27","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":3.47},
  {"year":1970,"rank":"28","country":"China","agglomeration":"Tianjin","population":3.32},
  {"year":1970,"rank":"29","country":"Iran (Islamic Republic of)","agglomeration":"Tehran","population":3.29},
  {"year":1970,"rank":"30","country":"Germany","agglomeration":"Berlin","population":3.21},
  {"year":1975,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":26.61},
  {"year":1975,"rank":"2","country":"United States of America","agglomeration":"New York","population":15.88},
  {"year":1975,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":10.69},
  {"year":1975,"rank":"4","country":"Japan","agglomeration":"Osaka-Kobe","population":9.84},
  {"year":1975,"rank":"5","country":"Brazil","agglomeration":"São Paulo","population":9.61},
  {"year":1975,"rank":"6","country":"United States of America","agglomeration":"Los Angeles","population":8.93},
  {"year":1975,"rank":"7","country":"Argentina","agglomeration":"Buenos Aires","population":8.74},
  {"year":1975,"rank":"8","country":"France","agglomeration":"Paris","population":8.56},
  {"year":1975,"rank":"9","country":"India","agglomeration":"Calcutta","population":7.89},
  {"year":1975,"rank":"10","country":"Russian Federation","agglomeration":"Moscow","population":7.62},
  {"year":1975,"rank":"11","country":"Brazil","agglomeration":"Rio de Janeiro","population":7.56},
  {"year":1975,"rank":"12","country":"United Kingdom","agglomeration":"London","population":7.55},
  {"year":1975,"rank":"13","country":"United States of America","agglomeration":"Chicago","population":7.16},
  {"year":1975,"rank":"14","country":"India","agglomeration":"Bombay","population":7.08},
  {"year":1975,"rank":"15","country":"Republic of Korea","agglomeration":"Seoul","population":6.81},
  {"year":1975,"rank":"16","country":"Egypt","agglomeration":"Cairo","population":6.45},
  {"year":1975,"rank":"17","country":"China","agglomeration":"Shanghai","population":5.63},
  {"year":1975,"rank":"18","country":"Philippines","agglomeration":"Manila","population":5},
  {"year":1975,"rank":"19","country":"China","agglomeration":"Beijing","population":4.83},
  {"year":1975,"rank":"20","country":"Indonesia","agglomeration":"Jakarta","population":4.81},
  {"year":1975,"rank":"21","country":"United States of America","agglomeration":"Philadelphia","population":4.47},
  {"year":1975,"rank":"22","country":"India","agglomeration":"Delhi","population":4.43},
  {"year":1975,"rank":"23","country":"Russian Federation","agglomeration":"Saint Petersburg","population":4.33},
  {"year":1975,"rank":"24","country":"Iran (Islamic Republic of)","agglomeration":"Tehran","population":4.27},
  {"year":1975,"rank":"25","country":"Pakistan","agglomeration":"Karachi","population":3.99},
  {"year":1975,"rank":"26","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":3.91},
  {"year":1975,"rank":"27","country":"Spain","agglomeration":"Madrid","population":3.89},
  {"year":1975,"rank":"28","country":"United States of America","agglomeration":"Detroit","population":3.89},
  {"year":1975,"rank":"29","country":"Thailand","agglomeration":"Krung Thep (Bangkok)","population":3.84},
  {"year":1975,"rank":"30","country":"Peru","agglomeration":"Lima","population":3.7},
  {"year":1980,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":28.55},
  {"year":1980,"rank":"2","country":"United States of America","agglomeration":"New York","population":15.6},
  {"year":1980,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":13.01},
  {"year":1980,"rank":"4","country":"Brazil","agglomeration":"São Paulo","population":12.09},
  {"year":1980,"rank":"5","country":"Japan","agglomeration":"Osaka-Kobe","population":9.99},
  {"year":1980,"rank":"6","country":"United States of America","agglomeration":"Los Angeles","population":9.51},
  {"year":1980,"rank":"7","country":"Argentina","agglomeration":"Buenos Aires","population":9.42},
  {"year":1980,"rank":"8","country":"India","agglomeration":"Calcutta","population":9.03},
  {"year":1980,"rank":"9","country":"France","agglomeration":"Paris","population":8.67},
  {"year":1980,"rank":"10","country":"India","agglomeration":"Bombay","population":8.66},
  {"year":1980,"rank":"11","country":"Brazil","agglomeration":"Rio de Janeiro","population":8.58},
  {"year":1980,"rank":"12","country":"Republic of Korea","agglomeration":"Seoul","population":8.26},
  {"year":1980,"rank":"13","country":"Russian Federation","agglomeration":"Moscow","population":8.14},
  {"year":1980,"rank":"14","country":"United Kingdom","agglomeration":"London","population":7.66},
  {"year":1980,"rank":"15","country":"Egypt","agglomeration":"Cairo","population":7.35},
  {"year":1980,"rank":"16","country":"United States of America","agglomeration":"Chicago","population":7.22},
  {"year":1980,"rank":"17","country":"Indonesia","agglomeration":"Jakarta","population":5.98},
  {"year":1980,"rank":"18","country":"China","agglomeration":"Shanghai","population":5.97},
  {"year":1980,"rank":"19","country":"Philippines","agglomeration":"Manila","population":5.95},
  {"year":1980,"rank":"20","country":"India","agglomeration":"Delhi","population":5.56},
  {"year":1980,"rank":"21","country":"China","agglomeration":"Beijing","population":5.37},
  {"year":1980,"rank":"22","country":"Iran (Islamic Republic of)","agglomeration":"Tehran","population":5.08},
  {"year":1980,"rank":"23","country":"Pakistan","agglomeration":"Karachi","population":5.05},
  {"year":1980,"rank":"24","country":"Thailand","agglomeration":"Krung Thep (Bangkok)","population":4.72},
  {"year":1980,"rank":"25","country":"Russian Federation","agglomeration":"Saint Petersburg","population":4.64},
  {"year":1980,"rank":"26","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":4.62},
  {"year":1980,"rank":"27","country":"United States of America","agglomeration":"Philadelphia","population":4.54},
  {"year":1980,"rank":"28","country":"Peru","agglomeration":"Lima","population":4.44},
  {"year":1980,"rank":"29","country":"Turkey","agglomeration":"Istanbul","population":4.4},
  {"year":1980,"rank":"30","country":"Spain","agglomeration":"Madrid","population":4.25},
  {"year":1985,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":30.3},
  {"year":1985,"rank":"2","country":"United States of America","agglomeration":"New York","population":15.83},
  {"year":1985,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":14.11},
  {"year":1985,"rank":"4","country":"Brazil","agglomeration":"São Paulo","population":13.39},
  {"year":1985,"rank":"5","country":"India","agglomeration":"Bombay","population":10.39},
  {"year":1985,"rank":"6","country":"Japan","agglomeration":"Osaka-Kobe","population":10.35},
  {"year":1985,"rank":"7","country":"United States of America","agglomeration":"Los Angeles","population":10.18},
  {"year":1985,"rank":"8","country":"Argentina","agglomeration":"Buenos Aires","population":9.96},
  {"year":1985,"rank":"9","country":"India","agglomeration":"Calcutta","population":9.95},
  {"year":1985,"rank":"10","country":"Republic of Korea","agglomeration":"Seoul","population":9.55},
  {"year":1985,"rank":"11","country":"Brazil","agglomeration":"Rio de Janeiro","population":9.09},
  {"year":1985,"rank":"12","country":"France","agglomeration":"Paris","population":8.96},
  {"year":1985,"rank":"13","country":"Russian Federation","agglomeration":"Moscow","population":8.58},
  {"year":1985,"rank":"14","country":"Egypt","agglomeration":"Cairo","population":8.33},
  {"year":1985,"rank":"15","country":"United Kingdom","agglomeration":"London","population":7.67},
  {"year":1985,"rank":"16","country":"India","agglomeration":"Delhi","population":7.33},
  {"year":1985,"rank":"17","country":"United States of America","agglomeration":"Chicago","population":7.29},
  {"year":1985,"rank":"18","country":"Indonesia","agglomeration":"Jakarta","population":7.01},
  {"year":1985,"rank":"19","country":"Philippines","agglomeration":"Manila","population":6.89},
  {"year":1985,"rank":"20","country":"China","agglomeration":"Shanghai","population":6.85},
  {"year":1985,"rank":"21","country":"Pakistan","agglomeration":"Karachi","population":6.03},
  {"year":1985,"rank":"22","country":"China","agglomeration":"Beijing","population":6.02},
  {"year":1985,"rank":"23","country":"Iran (Islamic Republic of)","agglomeration":"Tehran","population":5.84},
  {"year":1985,"rank":"24","country":"Turkey","agglomeration":"Istanbul","population":5.41},
  {"year":1985,"rank":"25","country":"Thailand","agglomeration":"Krung Thep (Bangkok)","population":5.28},
  {"year":1985,"rank":"26","country":"Peru","agglomeration":"Lima","population":5.12},
  {"year":1985,"rank":"27","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":5.03},
  {"year":1985,"rank":"28","country":"Russian Federation","agglomeration":"Saint Petersburg","population":4.84},
  {"year":1985,"rank":"29","country":"India","agglomeration":"Chennai (Madras)","population":4.75},
  {"year":1985,"rank":"30","country":"Bangladesh","agglomeration":"Dhaka","population":4.66},
  {"year":1990,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":32.53},
  {"year":1990,"rank":"2","country":"United States of America","agglomeration":"New York","population":16.09},
  {"year":1990,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":15.31},
  {"year":1990,"rank":"4","country":"Brazil","agglomeration":"São Paulo","population":14.78},
  {"year":1990,"rank":"5","country":"India","agglomeration":"Bombay","population":12.44},
  {"year":1990,"rank":"6","country":"Japan","agglomeration":"Osaka-Kobe","population":11.04},
  {"year":1990,"rank":"7","country":"India","agglomeration":"Calcutta","population":10.89},
  {"year":1990,"rank":"8","country":"United States of America","agglomeration":"Los Angeles","population":10.88},
  {"year":1990,"rank":"9","country":"Republic of Korea","agglomeration":"Seoul","population":10.54},
  {"year":1990,"rank":"10","country":"Argentina","agglomeration":"Buenos Aires","population":10.51},
  {"year":1990,"rank":"11","country":"India","agglomeration":"Delhi","population":9.73},
  {"year":1990,"rank":"12","country":"Brazil","agglomeration":"Rio de Janeiro","population":9.59},
  {"year":1990,"rank":"13","country":"France","agglomeration":"Paris","population":9.33},
  {"year":1990,"rank":"14","country":"Egypt","agglomeration":"Cairo","population":9.06},
  {"year":1990,"rank":"15","country":"Russian Federation","agglomeration":"Moscow","population":8.99},
  {"year":1990,"rank":"16","country":"Indonesia","agglomeration":"Jakarta","population":8.18},
  {"year":1990,"rank":"17","country":"Philippines","agglomeration":"Manila","population":7.97},
  {"year":1990,"rank":"18","country":"China","agglomeration":"Shanghai","population":7.82},
  {"year":1990,"rank":"19","country":"United Kingdom","agglomeration":"London","population":7.65},
  {"year":1990,"rank":"20","country":"United States of America","agglomeration":"Chicago","population":7.37},
  {"year":1990,"rank":"21","country":"Pakistan","agglomeration":"Karachi","population":7.15},
  {"year":1990,"rank":"22","country":"China","agglomeration":"Beijing","population":6.79},
  {"year":1990,"rank":"23","country":"Bangladesh","agglomeration":"Dhaka","population":6.62},
  {"year":1990,"rank":"24","country":"Turkey","agglomeration":"Istanbul","population":6.55},
  {"year":1990,"rank":"25","country":"Iran (Islamic Republic of)","agglomeration":"Tehran","population":6.36},
  {"year":1990,"rank":"26","country":"Thailand","agglomeration":"Krung Thep (Bangkok)","population":5.89},
  {"year":1990,"rank":"27","country":"Peru","agglomeration":"Lima","population":5.84},
  {"year":1990,"rank":"28","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":5.77},
  {"year":1990,"rank":"29","country":"India","agglomeration":"Chennai (Madras)","population":5.34},
  {"year":1990,"rank":"30","country":"Russian Federation","agglomeration":"Saint Petersburg","population":4.99},
  {"year":1995,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":33.59},
  {"year":1995,"rank":"2","country":"United States of America","agglomeration":"New York","population":16.94},
  {"year":1995,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":16.81},
  {"year":1995,"rank":"4","country":"Brazil","agglomeration":"São Paulo","population":15.95},
  {"year":1995,"rank":"5","country":"India","agglomeration":"Bombay","population":14.31},
  {"year":1995,"rank":"6","country":"India","agglomeration":"Delhi","population":12.41},
  {"year":1995,"rank":"7","country":"India","agglomeration":"Calcutta","population":11.92},
  {"year":1995,"rank":"8","country":"United States of America","agglomeration":"Los Angeles","population":11.34},
  {"year":1995,"rank":"9","country":"Argentina","agglomeration":"Buenos Aires","population":11.15},
  {"year":1995,"rank":"10","country":"Japan","agglomeration":"Osaka-Kobe","population":11.05},
  {"year":1995,"rank":"11","country":"China","agglomeration":"Shanghai","population":10.45},
  {"year":1995,"rank":"12","country":"Republic of Korea","agglomeration":"Seoul","population":10.26},
  {"year":1995,"rank":"13","country":"Brazil","agglomeration":"Rio de Janeiro","population":10.17},
  {"year":1995,"rank":"14","country":"Egypt","agglomeration":"Cairo","population":9.71},
  {"year":1995,"rank":"15","country":"France","agglomeration":"Paris","population":9.51},
  {"year":1995,"rank":"16","country":"Philippines","agglomeration":"Manila","population":9.4},
  {"year":1995,"rank":"17","country":"Russian Federation","agglomeration":"Moscow","population":9.2},
  {"year":1995,"rank":"18","country":"Pakistan","agglomeration":"Karachi","population":8.47},
  {"year":1995,"rank":"19","country":"Bangladesh","agglomeration":"Dhaka","population":8.33},
  {"year":1995,"rank":"20","country":"Indonesia","agglomeration":"Jakarta","population":8.32},
  {"year":1995,"rank":"21","country":"China","agglomeration":"Beijing","population":8.31},
  {"year":1995,"rank":"22","country":"United Kingdom","agglomeration":"London","population":7.91},
  {"year":1995,"rank":"23","country":"United States of America","agglomeration":"Chicago","population":7.84},
  {"year":1995,"rank":"24","country":"Turkey","agglomeration":"Istanbul","population":7.67},
  {"year":1995,"rank":"25","country":"Iran (Islamic Republic of)","agglomeration":"Tehran","population":6.69},
  {"year":1995,"rank":"26","country":"Peru","agglomeration":"Lima","population":6.58},
  {"year":1995,"rank":"27","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":6.14},
  {"year":1995,"rank":"28","country":"Thailand","agglomeration":"Krung Thep (Bangkok)","population":6.11},
  {"year":1995,"rank":"29","country":"Nigeria","agglomeration":"Lagos","population":5.98},
  {"year":1995,"rank":"30","country":"India","agglomeration":"Chennai (Madras)","population":5.84},
  {"year":2000,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":34.45},
  {"year":2000,"rank":"2","country":"Mexico","agglomeration":"Mexico City","population":18.02},
  {"year":2000,"rank":"3","country":"United States of America","agglomeration":"New York","population":17.85},
  {"year":2000,"rank":"4","country":"Brazil","agglomeration":"São Paulo","population":17.1},
  {"year":2000,"rank":"5","country":"India","agglomeration":"Bombay","population":16.37},
  {"year":2000,"rank":"6","country":"India","agglomeration":"Delhi","population":15.73},
  {"year":2000,"rank":"7","country":"China","agglomeration":"Shanghai","population":13.96},
  {"year":2000,"rank":"8","country":"India","agglomeration":"Calcutta","population":13.06},
  {"year":2000,"rank":"9","country":"Argentina","agglomeration":"Buenos Aires","population":11.85},
  {"year":2000,"rank":"10","country":"United States of America","agglomeration":"Los Angeles","population":11.81},
  {"year":2000,"rank":"11","country":"Japan","agglomeration":"Osaka-Kobe","population":11.17},
  {"year":2000,"rank":"12","country":"Brazil","agglomeration":"Rio de Janeiro","population":10.8},
  {"year":2000,"rank":"13","country":"Bangladesh","agglomeration":"Dhaka","population":10.28},
  {"year":2000,"rank":"14","country":"Egypt","agglomeration":"Cairo","population":10.17},
  {"year":2000,"rank":"15","country":"China","agglomeration":"Beijing","population":10.16},
  {"year":2000,"rank":"16","country":"Pakistan","agglomeration":"Karachi","population":10.03},
  {"year":2000,"rank":"17","country":"Russian Federation","agglomeration":"Moscow","population":10},
  {"year":2000,"rank":"18","country":"Philippines","agglomeration":"Manila","population":9.96},
  {"year":2000,"rank":"19","country":"Republic of Korea","agglomeration":"Seoul","population":9.92},
  {"year":2000,"rank":"20","country":"France","agglomeration":"Paris","population":9.74},
  {"year":2000,"rank":"21","country":"Turkey","agglomeration":"Istanbul","population":8.74},
  {"year":2000,"rank":"22","country":"Indonesia","agglomeration":"Jakarta","population":8.39},
  {"year":2000,"rank":"23","country":"United States of America","agglomeration":"Chicago","population":8.33},
  {"year":2000,"rank":"24","country":"United Kingdom","agglomeration":"London","population":8.22},
  {"year":2000,"rank":"25","country":"China","agglomeration":"Chongqing","population":7.44},
  {"year":2000,"rank":"26","country":"China","agglomeration":"Guangzhou, Guangdong","population":7.33},
  {"year":2000,"rank":"27","country":"Peru","agglomeration":"Lima","population":7.29},
  {"year":2000,"rank":"28","country":"Nigeria","agglomeration":"Lagos","population":7.28},
  {"year":2000,"rank":"29","country":"Iran (Islamic Republic of)","agglomeration":"Tehran","population":6.88},
  {"year":2000,"rank":"30","country":"China, Hong Kong SAR","agglomeration":"Hong Kong","population":6.78},
  {"year":2005,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":35.62},
  {"year":2005,"rank":"2","country":"United States of America","agglomeration":"New York","population":18.89},
  {"year":2005,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":18.73},
  {"year":2005,"rank":"4","country":"India","agglomeration":"Delhi","population":18.67},
  {"year":2005,"rank":"5","country":"Brazil","agglomeration":"São Paulo","population":18.33},
  {"year":2005,"rank":"6","country":"India","agglomeration":"Bombay","population":17.89},
  {"year":2005,"rank":"7","country":"China","agglomeration":"Shanghai","population":16.59},
  {"year":2005,"rank":"8","country":"India","agglomeration":"Calcutta","population":13.7},
  {"year":2005,"rank":"9","country":"Bangladesh","agglomeration":"Dhaka","population":12.61},
  {"year":2005,"rank":"10","country":"Argentina","agglomeration":"Buenos Aires","population":12.59},
  {"year":2005,"rank":"11","country":"United States of America","agglomeration":"Los Angeles","population":12.41},
  {"year":2005,"rank":"12","country":"China","agglomeration":"Beijing","population":12.35},
  {"year":2005,"rank":"13","country":"Pakistan","agglomeration":"Karachi","population":11.74},
  {"year":2005,"rank":"14","country":"Brazil","agglomeration":"Rio de Janeiro","population":11.37},
  {"year":2005,"rank":"15","country":"Japan","agglomeration":"Osaka-Kobe","population":11.26},
  {"year":2005,"rank":"16","country":"Philippines","agglomeration":"Manila","population":10.76},
  {"year":2005,"rank":"17","country":"Russian Federation","agglomeration":"Moscow","population":10.75},
  {"year":2005,"rank":"18","country":"Egypt","agglomeration":"Cairo","population":10.56},
  {"year":2005,"rank":"19","country":"France","agglomeration":"Paris","population":10.11},
  {"year":2005,"rank":"20","country":"Republic of Korea","agglomeration":"Seoul","population":9.83},
  {"year":2005,"rank":"21","country":"Turkey","agglomeration":"Istanbul","population":9.75},
  {"year":2005,"rank":"22","country":"Indonesia","agglomeration":"Jakarta","population":8.99},
  {"year":2005,"rank":"23","country":"United States of America","agglomeration":"Chicago","population":8.9},
  {"year":2005,"rank":"24","country":"Nigeria","agglomeration":"Lagos","population":8.86},
  {"year":2005,"rank":"25","country":"China","agglomeration":"Guangzhou, Guangdong","population":8.85},
  {"year":2005,"rank":"26","country":"China","agglomeration":"Chongqing","population":8.6},
  {"year":2005,"rank":"27","country":"United Kingdom","agglomeration":"London","population":8.55},
  {"year":2005,"rank":"28","country":"China","agglomeration":"Shenzhen","population":8.41},
  {"year":2005,"rank":"29","country":"Peru","agglomeration":"Lima","population":8.08},
  {"year":2005,"rank":"30","country":"China","agglomeration":"Wuhan","population":7.74},
  {"year":2010,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":36.93},
  {"year":2010,"rank":"2","country":"India","agglomeration":"Delhi","population":21.94},
  {"year":2010,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":20.14},
  {"year":2010,"rank":"4","country":"United States of America","agglomeration":"New York","population":20.1},
  {"year":2010,"rank":"5","country":"Brazil","agglomeration":"São Paulo","population":19.65},
  {"year":2010,"rank":"6","country":"China","agglomeration":"Shanghai","population":19.55},
  {"year":2010,"rank":"7","country":"India","agglomeration":"Bombay","population":19.42},
  {"year":2010,"rank":"8","country":"China","agglomeration":"Beijing","population":15},
  {"year":2010,"rank":"9","country":"Bangladesh","agglomeration":"Dhaka","population":14.93},
  {"year":2010,"rank":"10","country":"India","agglomeration":"Calcutta","population":14.28},
  {"year":2010,"rank":"11","country":"Pakistan","agglomeration":"Karachi","population":13.5},
  {"year":2010,"rank":"12","country":"Argentina","agglomeration":"Buenos Aires","population":13.37},
  {"year":2010,"rank":"13","country":"United States of America","agglomeration":"Los Angeles","population":13.22},
  {"year":2010,"rank":"14","country":"Brazil","agglomeration":"Rio de Janeiro","population":11.87},
  {"year":2010,"rank":"15","country":"Philippines","agglomeration":"Manila","population":11.65},
  {"year":2010,"rank":"16","country":"Russian Federation","agglomeration":"Moscow","population":11.47},
  {"year":2010,"rank":"17","country":"Japan","agglomeration":"Osaka-Kobe","population":11.43},
  {"year":2010,"rank":"18","country":"Egypt","agglomeration":"Cairo","population":11.03},
  {"year":2010,"rank":"19","country":"Turkey","agglomeration":"Istanbul","population":10.95},
  {"year":2010,"rank":"20","country":"Nigeria","agglomeration":"Lagos","population":10.79},
  {"year":2010,"rank":"21","country":"France","agglomeration":"Paris","population":10.52},
  {"year":2010,"rank":"22","country":"China","agglomeration":"Guangzhou, Guangdong","population":10.49},
  {"year":2010,"rank":"23","country":"China","agglomeration":"Shenzhen","population":10.22},
  {"year":2010,"rank":"24","country":"Republic of Korea","agglomeration":"Seoul","population":9.75},
  {"year":2010,"rank":"25","country":"China","agglomeration":"Chongqing","population":9.73},
  {"year":2010,"rank":"26","country":"Indonesia","agglomeration":"Jakarta","population":9.63},
  {"year":2010,"rank":"27","country":"United States of America","agglomeration":"Chicago","population":9.54},
  {"year":2010,"rank":"28","country":"Peru","agglomeration":"Lima","population":8.95},
  {"year":2010,"rank":"29","country":"United Kingdom","agglomeration":"London","population":8.92},
  {"year":2010,"rank":"30","country":"China","agglomeration":"Wuhan","population":8.9},
  {"year":2011,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":37.22},
  {"year":2011,"rank":"2","country":"India","agglomeration":"Delhi","population":22.65},
  {"year":2011,"rank":"3","country":"Mexico","agglomeration":"Mexico City","population":20.45},
  {"year":2011,"rank":"4","country":"United States of America","agglomeration":"New York","population":20.35},
  {"year":2011,"rank":"5","country":"China","agglomeration":"Shanghai","population":20.21},
  {"year":2011,"rank":"6","country":"Brazil","agglomeration":"São Paulo","population":19.92},
  {"year":2011,"rank":"7","country":"India","agglomeration":"Bombay","population":19.74},
  {"year":2011,"rank":"8","country":"China","agglomeration":"Beijing","population":15.59},
  {"year":2011,"rank":"9","country":"Bangladesh","agglomeration":"Dhaka","population":15.39},
  {"year":2011,"rank":"10","country":"India","agglomeration":"Calcutta","population":14.4},
  {"year":2011,"rank":"11","country":"Pakistan","agglomeration":"Karachi","population":13.88},
  {"year":2011,"rank":"12","country":"Argentina","agglomeration":"Buenos Aires","population":13.53},
  {"year":2011,"rank":"13","country":"United States of America","agglomeration":"Los Angeles","population":13.4},
  {"year":2011,"rank":"14","country":"Brazil","agglomeration":"Rio de Janeiro","population":11.96},
  {"year":2011,"rank":"15","country":"Philippines","agglomeration":"Manila","population":11.86},
  {"year":2011,"rank":"16","country":"Russian Federation","agglomeration":"Moscow","population":11.62},
  {"year":2011,"rank":"17","country":"Japan","agglomeration":"Osaka-Kobe","population":11.49},
  {"year":2011,"rank":"18","country":"Turkey","agglomeration":"Istanbul","population":11.25},
  {"year":2011,"rank":"19","country":"Nigeria","agglomeration":"Lagos","population":11.22},
  {"year":2011,"rank":"20","country":"Egypt","agglomeration":"Cairo","population":11.17},
  {"year":2011,"rank":"21","country":"China","agglomeration":"Guangzhou, Guangdong","population":10.85},
  {"year":2011,"rank":"22","country":"China","agglomeration":"Shenzhen","population":10.63},
  {"year":2011,"rank":"23","country":"France","agglomeration":"Paris","population":10.62},
  {"year":2011,"rank":"24","country":"China","agglomeration":"Chongqing","population":9.98},
  {"year":2011,"rank":"25","country":"Indonesia","agglomeration":"Jakarta","population":9.77},
  {"year":2011,"rank":"26","country":"Republic of Korea","agglomeration":"Seoul","population":9.74},
  {"year":2011,"rank":"27","country":"United States of America","agglomeration":"Chicago","population":9.68},
  {"year":2011,"rank":"28","country":"China","agglomeration":"Wuhan","population":9.16},
  {"year":2011,"rank":"29","country":"Peru","agglomeration":"Lima","population":9.13},
  {"year":2011,"rank":"30","country":"United Kingdom","agglomeration":"London","population":9.01},
  {"year":2015,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":38.2},
  {"year":2015,"rank":"2","country":"India","agglomeration":"Delhi","population":25.63},
  {"year":2015,"rank":"3","country":"China","agglomeration":"Shanghai","population":22.96},
  {"year":2015,"rank":"4","country":"Mexico","agglomeration":"Mexico City","population":21.71},
  {"year":2015,"rank":"5","country":"United States of America","agglomeration":"New York","population":21.33},
  {"year":2015,"rank":"6","country":"India","agglomeration":"Bombay","population":21.21},
  {"year":2015,"rank":"7","country":"Brazil","agglomeration":"São Paulo","population":21.03},
  {"year":2015,"rank":"8","country":"China","agglomeration":"Beijing","population":18.08},
  {"year":2015,"rank":"9","country":"Bangladesh","agglomeration":"Dhaka","population":17.38},
  {"year":2015,"rank":"10","country":"Pakistan","agglomeration":"Karachi","population":15.5},
  {"year":2015,"rank":"11","country":"India","agglomeration":"Calcutta","population":15.08},
  {"year":2015,"rank":"12","country":"Argentina","agglomeration":"Buenos Aires","population":14.15},
  {"year":2015,"rank":"13","country":"United States of America","agglomeration":"Los Angeles","population":14.08},
  {"year":2015,"rank":"14","country":"Nigeria","agglomeration":"Lagos","population":13.12},
  {"year":2015,"rank":"15","country":"Philippines","agglomeration":"Manila","population":12.86},
  {"year":2015,"rank":"16","country":"Turkey","agglomeration":"Istanbul","population":12.46},
  {"year":2015,"rank":"17","country":"China","agglomeration":"Guangzhou, Guangdong","population":12.39},
  {"year":2015,"rank":"18","country":"Brazil","agglomeration":"Rio de Janeiro","population":12.38},
  {"year":2015,"rank":"19","country":"China","agglomeration":"Shenzhen","population":12.34},
  {"year":2015,"rank":"20","country":"Russian Federation","agglomeration":"Moscow","population":12.14},
  {"year":2015,"rank":"21","country":"Egypt","agglomeration":"Cairo","population":11.94},
  {"year":2015,"rank":"22","country":"Japan","agglomeration":"Osaka-Kobe","population":11.78},
  {"year":2015,"rank":"23","country":"France","agglomeration":"Paris","population":11.1},
  {"year":2015,"rank":"24","country":"China","agglomeration":"Chongqing","population":11.05},
  {"year":2015,"rank":"25","country":"Indonesia","agglomeration":"Jakarta","population":10.47},
  {"year":2015,"rank":"26","country":"Democratic Republic of the Congo","agglomeration":"Kinshasa","population":10.31},
  {"year":2015,"rank":"27","country":"China","agglomeration":"Wuhan","population":10.26},
  {"year":2015,"rank":"28","country":"United States of America","agglomeration":"Chicago","population":10.2},
  {"year":2015,"rank":"29","country":"India","agglomeration":"Bangalore","population":10.02},
  {"year":2015,"rank":"30","country":"India","agglomeration":"Chennai (Madras)","population":9.89},
  {"year":2020,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":38.71},
  {"year":2020,"rank":"2","country":"India","agglomeration":"Delhi","population":29.27},
  {"year":2020,"rank":"3","country":"China","agglomeration":"Shanghai","population":26.12},
  {"year":2020,"rank":"4","country":"India","agglomeration":"Bombay","population":23.66},
  {"year":2020,"rank":"5","country":"Mexico","agglomeration":"Mexico City","population":23.24},
  {"year":2020,"rank":"6","country":"United States of America","agglomeration":"New York","population":22.49},
  {"year":2020,"rank":"7","country":"Brazil","agglomeration":"São Paulo","population":22.24},
  {"year":2020,"rank":"8","country":"China","agglomeration":"Beijing","population":20.78},
  {"year":2020,"rank":"9","country":"Bangladesh","agglomeration":"Dhaka","population":20.06},
  {"year":2020,"rank":"10","country":"Pakistan","agglomeration":"Karachi","population":17.73},
  {"year":2020,"rank":"11","country":"India","agglomeration":"Calcutta","population":16.65},
  {"year":2020,"rank":"12","country":"Nigeria","agglomeration":"Lagos","population":15.83},
  {"year":2020,"rank":"13","country":"United States of America","agglomeration":"Los Angeles","population":14.91},
  {"year":2020,"rank":"14","country":"Argentina","agglomeration":"Buenos Aires","population":14.88},
  {"year":2020,"rank":"15","country":"Philippines","agglomeration":"Manila","population":14.43},
  {"year":2020,"rank":"16","country":"China","agglomeration":"Shenzhen","population":14.22},
  {"year":2020,"rank":"17","country":"China","agglomeration":"Guangzhou, Guangdong","population":14.17},
  {"year":2020,"rank":"18","country":"Turkey","agglomeration":"Istanbul","population":13.79},
  {"year":2020,"rank":"19","country":"Egypt","agglomeration":"Cairo","population":13.25},
  {"year":2020,"rank":"20","country":"Brazil","agglomeration":"Rio de Janeiro","population":13.02},
  {"year":2020,"rank":"21","country":"China","agglomeration":"Chongqing","population":12.48},
  {"year":2020,"rank":"22","country":"Russian Federation","agglomeration":"Moscow","population":12.48},
  {"year":2020,"rank":"23","country":"Democratic Republic of the Congo","agglomeration":"Kinshasa","population":12.32},
  {"year":2020,"rank":"24","country":"Japan","agglomeration":"Osaka-Kobe","population":12},
  {"year":2020,"rank":"25","country":"France","agglomeration":"Paris","population":11.68},
  {"year":2020,"rank":"26","country":"India","agglomeration":"Bangalore","population":11.64},
  {"year":2020,"rank":"27","country":"China","agglomeration":"Wuhan","population":11.64},
  {"year":2020,"rank":"28","country":"Indonesia","agglomeration":"Jakarta","population":11.64},
  {"year":2020,"rank":"29","country":"India","agglomeration":"Chennai (Madras)","population":11.32},
  {"year":2020,"rank":"30","country":"China","agglomeration":"Tianjin","population":10.92},
  {"year":2025,"rank":"1","country":"Japan","agglomeration":"Tokyo","population":38.66},
  {"year":2025,"rank":"2","country":"India","agglomeration":"Delhi","population":32.94},
  {"year":2025,"rank":"3","country":"China","agglomeration":"Shanghai","population":28.4},
  {"year":2025,"rank":"4","country":"India","agglomeration":"Bombay","population":26.56},
  {"year":2025,"rank":"5","country":"Mexico","agglomeration":"Mexico City","population":24.58},
  {"year":2025,"rank":"6","country":"United States of America","agglomeration":"New York","population":23.57},
  {"year":2025,"rank":"7","country":"Brazil","agglomeration":"São Paulo","population":23.17},
  {"year":2025,"rank":"8","country":"Bangladesh","agglomeration":"Dhaka","population":22.91},
  {"year":2025,"rank":"9","country":"China","agglomeration":"Beijing","population":22.63},
  {"year":2025,"rank":"10","country":"Pakistan","agglomeration":"Karachi","population":20.19},
  {"year":2025,"rank":"11","country":"Nigeria","agglomeration":"Lagos","population":18.86},
  {"year":2025,"rank":"12","country":"India","agglomeration":"Calcutta","population":18.71},
  {"year":2025,"rank":"13","country":"Philippines","agglomeration":"Manila","population":16.28},
  {"year":2025,"rank":"14","country":"United States of America","agglomeration":"Los Angeles","population":15.69},
  {"year":2025,"rank":"15","country":"China","agglomeration":"Shenzhen","population":15.54},
  {"year":2025,"rank":"16","country":"Argentina","agglomeration":"Buenos Aires","population":15.52},
  {"year":2025,"rank":"17","country":"China","agglomeration":"Guangzhou, Guangdong","population":15.47},
  {"year":2025,"rank":"18","country":"Turkey","agglomeration":"Istanbul","population":14.9},
  {"year":2025,"rank":"19","country":"Egypt","agglomeration":"Cairo","population":14.74},
  {"year":2025,"rank":"20","country":"Democratic Republic of the Congo","agglomeration":"Kinshasa","population":14.54},
  {"year":2025,"rank":"21","country":"China","agglomeration":"Chongqing","population":13.63},
  {"year":2025,"rank":"22","country":"Brazil","agglomeration":"Rio de Janeiro","population":13.62},
  {"year":2025,"rank":"23","country":"India","agglomeration":"Bangalore","population":13.19},
  {"year":2025,"rank":"24","country":"Indonesia","agglomeration":"Jakarta","population":12.82},
  {"year":2025,"rank":"25","country":"India","agglomeration":"Chennai (Madras)","population":12.81},
  {"year":2025,"rank":"26","country":"China","agglomeration":"Wuhan","population":12.73},
  {"year":2025,"rank":"27","country":"Russian Federation","agglomeration":"Moscow","population":12.58},
  {"year":2025,"rank":"28","country":"France","agglomeration":"Paris","population":12.16},
  {"year":2025,"rank":"29","country":"Japan","agglomeration":"Osaka-Kobe","population":12.03},
  {"year":2025,"rank":"30","country":"China","agglomeration":"Tianjin","population":11.93}
];

});
