define([
  "d3", 
  "d3_tip",
  "draw",
  "base_config",
  "utils/utils",
  "mixins/data_methods",
  "mixins/layout_methods",
  "mixins/scale_methods",
  "mixins/axis_methods",
  "mixins/scaffolding",
  "bar/config",
  "bar/bar_methods", 
  "bar/scaffolding",
  "bar/bar",
  "line/config",
  "line/scaffolding",
  "line/line",
  "circle/config",
  "circle/scaffolding",
  "circle/circle",
  //"frame/states",
  //"frame/state_machine",
  //"frame/frame"
], function(
  d3, 
  d3_tip,
  draw, 
  base_config, 
  utils, 
  data_methods, 
  layout_methods, 
  scale_methods,
  axis_methods,
  scaffolding,
  bar_config,
  bar_methods,
  bar_scaffolding,
  Bar, 
  line_config,
  line_scaffolding,
  Line,
  circle_config,
  circle_scaffolding,
  Circle
  //states, 
  //StateMachine, 
  //Frame
) {

  d3.d3_tip = d3_tip;

  return {
    d3: d3,
    draw: draw,
    base_config: base_config,
    utils: utils,
    data_methods: data_methods,
    layout_methods: layout_methods,
    scale_methods: scale_methods,
    axis_methods: axis_methods,
    scaffolding: scaffolding,
    bar_config: bar_config,
    bar_methods: bar_methods,
    bar_scaffolding: bar_scaffolding,
    Bar: Bar,
    line_config: line_config,
    line_scaffolding: line_scaffolding,
    Line: Line,
    circle_config: circle_config,
    circle_scaffolding: circle_scaffolding,
    Circle: Circle,
    //Frame: Frame,
    //states: states, 
    //StateMachine: StateMachine,
  };

});

